name: windows

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.3.1
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.4'
        target: 'desktop'
        dir: '${{github.workspace}}/qt/'
        modules: qtwebengine qtwebchannel qtpositioning qt5compat
    - name: Install zlib
      shell: bash
      run: |
        vcpkg install zlib:x64-windows-static-md
    - name: Install QuaZIP
      shell: bash
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}}
      run: |
        mkdir -p quazip_1.4
        cd quazip_1.4
        git clone https://github.com/stachenov/quazip.git
        git -C quazip checkout 9d3aa3ee948c1cde5a9f873ecbc3bb229c1182ee  # v1.3_useQtXZlibInConfigCmake
        mkdir 'build'
        mkdir 'installed'
        cmake -S quazip -B build -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPES=Release -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static-md
        cmake --build build --config Release
        cmake --install build --prefix installed
        cd ..
    - name: Download OpenSSL
      shell: bash
      run: |
        # TODO: think of better openssl preparation, which is qt binary dependency and no source is required
        mkdir openssl
        cd openssl
        curl -O -L https://www.firedaemon.com/download-firedaemon-openssl-1-zip
        7z e download-firedaemon-openssl-1-zip openssl-1.1/x64/bin/libcrypto-1_1-x64.dll openssl-1.1/x64/bin/libssl-1_1-x64.dll
        dir
        cd ..
    - name: Build
      env:
        CMAKE_PREFIX_PATH: ${{env.Qt6_Dir}};${{github.workspace}}\quazip_1.4\installed
      run: |
        cd SlackLogViewer
        mkdir build
        mkdir SlackLogViewer_windows
        cmake -S ./ -B build -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX="SlackLogViewer_windows" -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPES=Release -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static-md -DOPENSSL_DIR="../openssl"
        cmake --build build --config Release
        cmake --install build
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: win
        path: SlackLogViewer/SlackLogViewer_windows